In [19]:
import pandas as pd

# Creating Series

In [20]:
colors = pd.Series(['red','green','blue'])

In [21]:
colors

0      red
1    green
2     blue
dtype: str

In [22]:
cars=pd.Series(['Tata','Honda','Maruti'])

In [23]:
cars

0      Tata
1     Honda
2    Maruti
dtype: str

# Creating first DataFrame

In [24]:
car_options=pd.DataFrame({"company":cars,"colour":colors})

In [25]:
car_options

  company colour
0    Tata    red
1   Honda  green
2  Maruti   blue

# Reading CSV

In [26]:
car_sales=pd.read_csv("car-sales.csv")
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

# Exporting To csv file

In [27]:
car_sales.to_csv('exported_car_sales.csv') # this will export data with index

In [28]:
car_sales_exported=pd.read_csv('exported_car_sales.csv')

In [29]:
car_sales_exported

   Unnamed: 0    Make Colour  Odometer (KM)  Doors       Price
0           0  Toyota  White         150043      4   $4,000.00
1           1   Honda    Red          87899      4   $5,000.00
2           2  Toyota   Blue          32549      3   $7,000.00
3           3     BMW  Black          11179      5  $22,000.00
4           4  Nissan  White         213095      4   $3,500.00
5           5  Toyota  Green          99213      4   $4,500.00
6           6   Honda   Blue          45698      4   $7,500.00
7           7   Honda   Blue          54738      4   $7,000.00
8           8  Toyota  White          60000      4   $6,250.00
9           9  Nissan  White          31600      4   $9,700.00

In [30]:
car_sales.to_csv('exported_sales_without_index.csv',index=False)

In [31]:
car_sales_exported_without_index=pd.read_csv('exported_sales_without_index.csv')

In [32]:
car_sales_exported_without_index

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

# Describe Pandas

In [33]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [34]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [45]:
car_sales.index #return number of items

RangeIndex(start=0, stop=10, step=1)

In [46]:
car_sales.describe() #give stats of number column only

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [37]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [40]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [41]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [43]:
car_sales['Doors'].sum()

np.int64(40)

In [44]:
len(car_sales)

10

# Select and View Data

## retun first few items

In [48]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [49]:
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [50]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [51]:
car_sales.tail(3)

     Make Colour  Odometer (KM)  Doors      Price
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00